on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

name: Check issues
jobs:
  link-checker:
    name: Check issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install --upgrade PyGitHub bs4
      - name: Labels
        if: ${{ github.event_name == 'schedule'}}
        env:
          BEHEER: ${{ secrets.BEHEER }}
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/labels.py
          python labels.py
      - name: Issues
        env:
          BEHEER: ${{ secrets.BEHEER }}
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/issues.py
          python issues.py
      - name: Clean-up
        run: rm -f labels.py issues.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update issue reports
          commit_user_name: GitHub Actions
          commit_user_email: api@logius.nl
          commit_author: Standaardenbeheer <api@logius.nl>
